src/Entity/ShortUrl.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShortUrlRepository")
 */
class ShortUrl
{
    public function __construct() {
        $this->date_create = new \DateTime();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $short_url;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_time;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getShortUrl(): ?string
    {
        return $this->short_url;
    }

    public function setShortUrl(?string $short_url): self
    {
        $this->short_url = $short_url;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(?\DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }
}

src/Entity/Stat.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StatRepository")
 */
class Stat
{
    public function __construct() {
        $this->date_visit = new \DateTime();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $ip;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_visit;

    /**
     * @ORM\Column(type="integer")
     */
    private $link_id;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $user_agent;

    /**
     * @return mixed
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * @param mixed $user_agent
     */
    public function setUserAgent($user_agent)
    {
        $this->user_agent = $user_agent;
    }

    /**
     * @return mixed
     */
    public function getLinkId()
    {
        return $this->link_id;
    }

    /**
     * @param mixed $link_id
     */
    public function setLinkId($link_id): void
    {
        $this->link_id = $link_id;
    }

    /**
     * @return mixed
     */
    public function getDateVisit()
    {
        return $this->date_visit;
    }

    /**
     * @param mixed $date_visit
     */
    public function setDateVisit($date_visit): void
    {
        $this->date_visit = $date_visit;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self {
        $this->location = $location;

        return $this;
    }
}

src/Controller/Admin.php
<?php

namespace App\Controller;

use App\Entity\Stat;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class Admin extends Controller {

    public function index( Request $request ) {
        if ( $url = $request->get('url') ) {

            $shortener = $this->container->get('Shortener');

            $linkId = $shortener->Decode($url);

            $em = $this->getDoctrine()->getManager();

            $stat = $em->getRepository(Stat::class)->findBy(['link_id' => $linkId]);

            return $this->render('shortener/stat.html.twig', ['stat' => $stat]);

        } else {
            return $this->redirect('/');
        }
    }
}

src/Controller/Shortener.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\ShortUrl;
use App\Entity\Stat;

class Shortener extends Controller {

    public function index(Request $request){
        if ( $url = filter_var($request->get('url', FILTER_VALIDATE_URL) ) ) {

            $shortener = $this->container->get('Shortener');

            $linkId = $shortener->Decode($url);

            $em = $this->getDoctrine()->getManager();

            $shortUrl = $em->getRepository(ShortUrl::class)->find($linkId);

            if ( $shortUrl ) {
                $userIp = $request->getClientIp();
                $userAgent = $request->headers->get('User-Agent');

                $stat = new Stat();

                $stat->setIp($userIp);
                $stat->setUserAgent($userAgent);
                $stat->setLinkId($linkId);

                $em->persist($stat);
                $em->flush();

                return $this->redirect($shortUrl->getLink());
            }
        }

        return $this->render('shortener/index.html.twig');
    }

    public function shortUrl(Request $request){
        $link = $request->get('link');

        if ( $link ) {
            $shortener = $this->container->get('Shortener');
            $em = $this->getDoctrine()->getManager();

            $shortUrl = new ShortUrl();

            $shortUrl->setLink($link);

            $em->persist($shortUrl);
            $em->flush();

            $shortLink = $shortener->Encode( $shortUrl->getId()-1 );
            $shortUrl->setShortUrl( $shortLink );

            $em->persist($shortUrl);
            $em->flush();
        }

        if ( !$shortLink )
            return $this->redirect('/');
        else
            return $this->render('shortener/short.html.twig', ['shortLink' => $shortLink]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/css/app.css') }}">
        {% endblock %}
    </head>
    <body>
        {% block body %}
            {% block content %}
            {% endblock %}
        {% endblock %}

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/shortener/index.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="container">
        <form method="post" action="/shortUrl">
            <label>Short url
                <input class="form-control" name="link" type="text" placeholder="input link to short">
            </label>
            <input class="btn btn-success" type="submit" value="short url">
        </form>
    </div>
{% endblock %}

templates/shortener/short.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="container">
        <h2>Links:</h2>

        <div class="row">
        <label>Short link
            <a href="http://{{ app.request.host }}/{{ shortLink }}">{{ app.request.host }}/{{ shortLink }}</a>
        </label>
        </div>
    <div class="row">
            <label>Stat link
            <a href="http://{{ app.request.host }}/stat/{{ shortLink }}">{{ app.request.host }}/stat/{{ shortLink }}</a>
        </label>
    </div>
    </div>
{% endblock %}

templates/shortener/stat.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="container">
        <h2>Statistic</h2>

    {% if stat %}
     <div class="row">
        <ul class="list-group">
        {% for s in stat %}
            <li class="list-group-item">
                <p>User Agent: {{ s.userAgent }}</p>
                <p>Visited from ip: {{ s.ip }} at {{ s.dateVisit|date }}</p>
            </li>
        {% endfor %}
        </ul>
     </div>
    {% else %}
        <p>Stat is empty</p>
    {% endif %}
    </div>
{% endblock %}